### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by hadim** [odinsbane/jfilament#1]
Hello @odinsbane and thank you for this nice plugin.

I am thinking about using some of the code of jFilament to adapt to IJ2 and allow scripting.

However, I didn't find any License for jFilament ? What are the term of use of the source code ? Would you release it under an open source license ?

**Comment by odinsbane** [comment]
Hello

I am in a haste at the moment, so I will take a look at making it more
obvious later. The pom.xml should mention the license? Also the file
COPYING describes the license.

https://github.com/odinsbane/jfilament/blob/developing/src/main/resources/snakeprogram3d/COPYING

Hope this helps.
Matt

**Comment by hadim** [comment]
Oh sorry I didn't see the license in the pom.xml. 

That's good :-)

So I'll share my modifications once it's done and then we'll see if we can incorporate them here or if it's better to keep it separated.

I plan to first convert it to IJ2, separate the algorithms from the code dealing with UI and then try to make it work with the ROI Manager (instead of using your custom UI).

**Comment by odinsbane** [comment]
Hello Hadim

Sounds like a pretty good plan. The main deforming algorithm is pretty
simple. There is a lot of UI type work though, especially for the editing
and manipulating curves. I am a bit curious though, which is the main part
you would want to have included in the ROI manager?

Cheers
mbs

**Comment by hadim** [comment]
To store the initial seeds of the snake.
